name: ZorionChat
version: ${project.version}
main: eu.lukatjee.zorionchat.zorionchat.ZorionChat
api-version: 1.16
authors: [ Lukatjee ]
description: Premium chat plugin for quality minecraft networks.
depend: [PlaceholderAPI]
commands:
  zorionchat:
    description: Base command.
    aliases: [ chat, zc ]